### ISSUE TITLE
editing site in Android

### ISSUE THREAD

**Issue by managingwholes** [Soil-Carbon-Coalition/atlasbiowork#21]
with the leaflet interface, editing sites on desktop seems to work well. 

With the app and Android, one can add and edit polygons but it does not work to add a point, and in Android one cannot add a new site (using site_edit.html) as the layer button is greyed out and nothing works.

**Comment by sheppard** [comment]
This was mostly an issue with [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw) which hasn't traditionally supported touch input.  It looks like they finally released a new version with touch support about a week ago.  I just updated the version of Leaflet.draw that comes with wq.app, so you should be able to get this working by upgrading wq.app to the latest master version and redeploying.

**Comment by managingwholes** [comment]
tried updating wq.app with the following command:

`pdonovan@atlasbiowork:/var/www/atlasbiowork$ sudo pip3 install -r https://github.com/wq/wq.app/archive/master.zip
[sudo] password for pdonovan:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 288, in run
    for req in parse_requirements(filename, finder=finder, options=options, session=session):
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1632, in parse_requirements
    req = InstallRequirement.from_line(line, comes_from, prereleases=getattr(options, "pre", None))
  File "/usr/lib/python3/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2986, in parse
    req, = parse_requirements(s)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2895, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
pkg_resources.RequirementParseError: Expected version spec in PK at 
Storing debug log for failure in /home/pdonovan/.pip/pip.log
pdonovan@atlasbiowork:/var/www/atlasbiowork$`

**Comment by sheppard** [comment]
`pip3 install` with `-r` is for when you are giving it a `requirements.txt` to work off of.  In this case remove the `-r` and add `--upgrade`.

**Comment by managingwholes** [comment]
thanks
